name: Mirroring
on: [push]
jobs:
  Mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          fetch-depth: 0
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-BDX-2-1-bschocolatine-quentin.loddo.git
          ssh_private_key:
            ${{secrets.ACTION_HEY}}