name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          name: ../../../tetris/B-PSU-200-BDX-2-1-tetris-romain.delaruelle/
          ref: origin/main
      - run: du -skh --exclude=".git"
